version: '2'
services:
  gin-app:
    container_name: gin-app
    build: .
    command: go run main.go
    volumes:
      - ./gin:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:3001"
    environment:
      PORT: 3001
  mongo:
    image: mongo
    ports:
    - "27016:27017"
